### ISSUE TITLE
A very, very, very long function body, more than 377 lines, and the recommended number is 15 for each function at most.

### ISSUE THREAD

**Issue by 0x61nas** [Hamdysaad20/JavaCollageProject#1]
https://github.com/Hamdysaad20/JavaCollageProject/blob/6ae9f3ca14713952dda9311f6ae1b32da6993fb4/JavaFXApplication1/src/javafxapplication1/Main.java#L45

**Comment by Hamdysaad20** [comment]
I'll work on that thank u.
